pipeline {
   agent {
   	label '10.30.80.220'
   }
   stages {
      stage('Hello') {
         steps {
            echo 'Hello World'
            sh './runservice start development'
         }
      }
   }
}

