pipeline {
   agent {
   	label '10.30.80.220'
   }
    environment {
        http_proxy='http://10.30.80.254:81'
        https_proxy='http://10.30.80.254:81'
    }
   stages {
      stage('Hello') {
         steps {
            echo 'Hello World'
            sh 'pwd'
         }
      }
   }
}

