pipeline {
   agent none
   stages {
   	  stage('Build') {
   	  	   agent {
		   	label 'master'
		   }
         steps {
            sh 'ant clean jar test'

         }
      }
      stage('Development') {
      	    environment {
		        http_proxy = 'http://10.30.80.254:81'
		        https_proxy    = 'http://10.30.80.254:81'
	   		 }
      	   agent {
		   	label '10.30.80.220'
		   }
         steps {
            sh './runservice restart development'
         }
      }
   }
}

